name: my_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - geopandas
  - matplotlib
  - seaborn
  - plotly
  - folium
  - branca
  - xgboost
  - scikit-learn
  - joblib
  - pip
  - flake8
  - pip:
      - streamlit-folium